FROM n8nio/n8n:1.41.1

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=heckertanmay
ENV N8N_BASIC_AUTH_PASSWORD=Utkarsh@2005
ENV N8N_HOST=0.0.0.0
ENV WEBHOOK_TUNNEL_URL=https://n8n-gbms.onrender.com
